import type { LanguageTheme } from '@/lib/github/github.types'

// Temas por lenguaje — PROJECT_CONTEXT.md §9
export const languageThemes: Record<string, LanguageTheme> = {
  TypeScript: {
    primary: '#38bdf8',
    secondary: '#1d4ed8',
    emissive: '#0ea5e9',
    label: 'TypeScript Ocean',
  },
  JavaScript: {
    primary: '#facc15',
    secondary: '#a16207',
    emissive: '#f59e0b',
    label: 'JavaScript Solar',
  },
  Python: {
    primary: '#22c55e',
    secondary: '#14532d',
    emissive: '#84cc16',
    label: 'Python Forest',
  },
  PHP: {
    primary: '#8b5cf6',
    secondary: '#4c1d95',
    emissive: '#a78bfa',
    label: 'PHP Violet Cloud',
  },
  Java: {
    primary: '#f97316',
    secondary: '#7c2d12',
    emissive: '#fb923c',
    label: 'Java Magma',
  },
  C: {
    primary: '#94a3b8',
    secondary: '#334155',
    emissive: '#cbd5e1',
    label: 'C Metal Core',
  },
  'C++': {
    primary: '#60a5fa',
    secondary: '#1e3a8a',
    emissive: '#93c5fd',
    label: 'C++ Blue Forge',
  },
  'C#': {
    primary: '#a855f7',
    secondary: '#3b0764',
    emissive: '#c084fc',
    label: 'C# Purple Forge',
  },
  Rust: {
    primary: '#f97316',
    secondary: '#431407',
    emissive: '#fdba74',
    label: 'Rust Iron Belt',
  },
  Go: {
    primary: '#06b6d4',
    secondary: '#164e63',
    emissive: '#22d3ee',
    label: 'Go Cyan Drift',
  },
  Ruby: {
    primary: '#f43f5e',
    secondary: '#881337',
    emissive: '#fb7185',
    label: 'Ruby Red Giant',
  },
  Swift: {
    primary: '#fb923c',
    secondary: '#7c2d12',
    emissive: '#fdba74',
    label: 'Swift Fire Ring',
  },
  Kotlin: {
    primary: '#a78bfa',
    secondary: '#4c1d95',
    emissive: '#c4b5fd',
    label: 'Kotlin Violet Pulse',
  },
  Shell: {
    primary: '#4ade80',
    secondary: '#14532d',
    emissive: '#86efac',
    label: 'Shell Green Terminal',
  },
  HTML: {
    primary: '#f97316',
    secondary: '#431407',
    emissive: '#fed7aa',
    label: 'HTML Lava Web',
  },
  CSS: {
    primary: '#38bdf8',
    secondary: '#0c4a6e',
    emissive: '#7dd3fc',
    label: 'CSS Blue Style',
  },
  Vue: {
    primary: '#42d392',
    secondary: '#064e3b',
    emissive: '#86efac',
    label: 'Vue Emerald Signal',
  },
  Astro: {
    primary: '#f472b6',
    secondary: '#581c87',
    emissive: '#fb7185',
    label: 'Astro Pink Flare',
  },
  Svelte: {
    primary: '#fb7185',
    secondary: '#7f1d1d',
    emissive: '#fdba74',
    label: 'Svelte Coral Spark',
  },
  MDX: {
    primary: '#c084fc',
    secondary: '#4c1d95',
    emissive: '#e9d5ff',
    label: 'MDX Violet Script',
  },
  Markdown: {
    primary: '#94a3b8',
    secondary: '#1e293b',
    emissive: '#e2e8f0',
    label: 'Markdown Silver Dust',
  },
  SCSS: {
    primary: '#f472b6',
    secondary: '#831843',
    emissive: '#f9a8d4',
    label: 'SCSS Rose Cloud',
  },
  Less: {
    primary: '#60a5fa',
    secondary: '#1e3a8a',
    emissive: '#93c5fd',
    label: 'Less Blue Circuit',
  },
  Blade: {
    primary: '#f43f5e',
    secondary: '#881337',
    emissive: '#fb7185',
    label: 'Blade Crimson Layer',
  },
  Dockerfile: {
    primary: '#38bdf8',
    secondary: '#075985',
    emissive: '#7dd3fc',
    label: 'Docker Blue Container',
  },
  Makefile: {
    primary: '#fbbf24',
    secondary: '#78350f',
    emissive: '#fde68a',
    label: 'Makefile Amber Forge',
  },
  CMake: {
    primary: '#22c55e',
    secondary: '#14532d',
    emissive: '#86efac',
    label: 'CMake Green Build',
  },
  Dart: {
    primary: '#22d3ee',
    secondary: '#164e63',
    emissive: '#67e8f9',
    label: 'Dart Cyan Jet',
  },
  Lua: {
    primary: '#818cf8',
    secondary: '#312e81',
    emissive: '#c4b5fd',
    label: 'Lua Indigo Moon',
  },
  PowerShell: {
    primary: '#60a5fa',
    secondary: '#1e40af',
    emissive: '#93c5fd',
    label: 'PowerShell Blue Console',
  },
  Batchfile: {
    primary: '#4ade80',
    secondary: '#14532d',
    emissive: '#86efac',
    label: 'Batchfile Terminal Belt',
  },
  'Jupyter Notebook': {
    primary: '#fb923c',
    secondary: '#7c2d12',
    emissive: '#fed7aa',
    label: 'Jupyter Amber Lab',
  },
  SQL: {
    primary: '#38bdf8',
    secondary: '#0f172a',
    emissive: '#7dd3fc',
    label: 'SQL Data Core',
  },
  GraphQL: {
    primary: '#f472b6',
    secondary: '#831843',
    emissive: '#f9a8d4',
    label: 'GraphQL Magenta Mesh',
  },
  YAML: {
    primary: '#facc15',
    secondary: '#713f12',
    emissive: '#fde047',
    label: 'YAML Gold Config',
  },
  JSON: {
    primary: '#facc15',
    secondary: '#713f12',
    emissive: '#fde047',
    label: 'JSON Gold Schema',
  },
  TOML: {
    primary: '#fb923c',
    secondary: '#7c2d12',
    emissive: '#fdba74',
    label: 'TOML Copper Config',
  },
  Prisma: {
    primary: '#38bdf8',
    secondary: '#0f172a',
    emissive: '#7dd3fc',
    label: 'Prisma Data Orbit',
  },
  Terraform: {
    primary: '#8b5cf6',
    secondary: '#4c1d95',
    emissive: '#c4b5fd',
    label: 'Terraform Violet Grid',
  },
  HCL: {
    primary: '#8b5cf6',
    secondary: '#4c1d95',
    emissive: '#c4b5fd',
    label: 'HCL Violet Grid',
  },
  Nix: {
    primary: '#60a5fa',
    secondary: '#1e3a8a',
    emissive: '#bfdbfe',
    label: 'Nix Frost Crystal',
  },
  Solidity: {
    primary: '#94a3b8',
    secondary: '#334155',
    emissive: '#cbd5e1',
    label: 'Solidity Alloy Chain',
  },
  Zig: {
    primary: '#fbbf24',
    secondary: '#78350f',
    emissive: '#fde68a',
    label: 'Zig Amber Bolt',
  },
  Elixir: {
    primary: '#c084fc',
    secondary: '#581c87',
    emissive: '#e9d5ff',
    label: 'Elixir Violet Pulse',
  },
  Erlang: {
    primary: '#f43f5e',
    secondary: '#881337',
    emissive: '#fb7185',
    label: 'Erlang Red Relay',
  },
  R: {
    primary: '#60a5fa',
    secondary: '#1e3a8a',
    emissive: '#93c5fd',
    label: 'R Blue Analyst',
  },
  Julia: {
    primary: '#a3e635',
    secondary: '#365314',
    emissive: '#bef264',
    label: 'Julia Lime Matrix',
  },
  Perl: {
    primary: '#38bdf8',
    secondary: '#075985',
    emissive: '#7dd3fc',
    label: 'Perl Cyan Script',
  },
  Scala: {
    primary: '#ef4444',
    secondary: '#7f1d1d',
    emissive: '#fca5a5',
    label: 'Scala Red Layer',
  },
  Haskell: {
    primary: '#a78bfa',
    secondary: '#4c1d95',
    emissive: '#c4b5fd',
    label: 'Haskell Violet Logic',
  },
  'Objective-C': {
    primary: '#60a5fa',
    secondary: '#1e3a8a',
    emissive: '#93c5fd',
    label: 'Objective-C Blue Runtime',
  },
  Mixed: {
    primary: '#a78bfa',
    secondary: '#312e81',
    emissive: '#c4b5fd',
    label: 'Mixed Code Signal',
  },
  default: {
    primary: '#a78bfa',
    secondary: '#312e81',
    emissive: '#c4b5fd',
    label: 'Mixed Code Signal',
  },
}

export function getLanguageTheme(language: string | null): LanguageTheme {
  if (!language) return languageThemes.Mixed
  return languageThemes[language] ?? languageThemes.default
}
