import { NebulaProfile } from '../github/github.types'
import { getLanguageTheme } from './languageTheme'

export const mockProfile: NebulaProfile = {
  user: {
    login: 'saidpereyra',
    name: 'Said Pereyra',
    avatarUrl: 'https://github.com/saidpereyra.png',
    htmlUrl: 'https://github.com/saidpereyra',
    publicRepos: 42,
    followers: 128,
    following: 50,
  },
  summary: {
    username: 'saidpereyra',
    totalStars: 540,
    totalForks: 32,
    topLanguage: 'TypeScript',
    activeRepos: 12,
    dominantEnergy: 'active',
  },
  repos: [
    {
      id: 1,
      name: 'code-nebula',
      description: 'Turn your GitHub into a living code galaxy.',
      url: 'https://github.com/saidpereyra/code-nebula',
      language: 'TypeScript',
      stars: 120,
      forks: 15,
      updatedAt: new Date().toISOString(),
      sizeScore: 0.8,
      activityScore: 0.9,
      energyScore: 0.85,
      orbitRadius: 4,
      orbitSpeed: 0.3,
      planetRadius: 0.8,
      theme: getLanguageTheme('TypeScript'),
    },
    {
      id: 2,
      name: 'react-glass-ui',
      description: 'A premium glassmorphism UI library for React.',
      url: 'https://github.com/saidpereyra/react-glass-ui',
      language: 'JavaScript',
      stars: 85,
      forks: 5,
      updatedAt: new Date(Date.now() - 100000000).toISOString(),
      sizeScore: 0.6,
      activityScore: 0.5,
      energyScore: 0.6,
      orbitRadius: 7,
      orbitSpeed: 0.2,
      planetRadius: 0.6,
      theme: getLanguageTheme('JavaScript'),
    },
    {
      id: 3,
      name: 'python-data-scraper',
      description: 'Async web scraper built with Python and BeautifulSoup.',
      url: 'https://github.com/saidpereyra/python-data-scraper',
      language: 'Python',
      stars: 45,
      forks: 10,
      updatedAt: new Date(Date.now() - 500000000).toISOString(),
      sizeScore: 0.5,
      activityScore: 0.3,
      energyScore: 0.4,
      orbitRadius: 10,
      orbitSpeed: 0.15,
      planetRadius: 0.5,
      theme: getLanguageTheme('Python'),
    },
    {
      id: 4,
      name: 'go-microservice',
      description: 'High performance microservice template in Go.',
      url: 'https://github.com/saidpereyra/go-microservice',
      language: 'Go',
      stars: 210,
      forks: 22,
      updatedAt: new Date(Date.now() - 20000000).toISOString(),
      sizeScore: 0.9,
      activityScore: 0.8,
      energyScore: 0.9,
      orbitRadius: 13,
      orbitSpeed: 0.25,
      planetRadius: 0.9,
      theme: getLanguageTheme('Go'),
    },
    {
      id: 5,
      name: 'css-animations',
      description: 'A collection of pure CSS animations.',
      url: 'https://github.com/saidpereyra/css-animations',
      language: 'CSS',
      stars: 60,
      forks: 2,
      updatedAt: new Date(Date.now() - 800000000).toISOString(),
      sizeScore: 0.4,
      activityScore: 0.2,
      energyScore: 0.3,
      orbitRadius: 16,
      orbitSpeed: 0.1,
      planetRadius: 0.4,
      theme: getLanguageTheme('CSS'),
    },
  ],
}
